baseURL = "https://klee30810.github.io/"

languageCode = "ko-kr"
DefaultContentLanguage = "ko"
title = "Kevin's Codex"
theme = "learn"

[Params]
	
	# can be "red", "blue", "green"
	themeVariant = "blue"

	[[menu.shortcuts]]
	name = "<i class='fas fa-tags'></i> Tags"
	url = "/tags"

# code highlight
[markup.highlight]
	codeFences = true
	guessSyntax = true
	lineNos = true
	lineNumbersInTable = true
	noClasses = true
	style = "paraiso-dark"

[outputs]
home = [ "HTML", "RSS", "JSON"]
